name: Fortify SCA Scan

on:
  push:
    branches:
      - main # specify the branch you want to scan
  pull_request:
    branches:
      - main # specify the branch you want to scan

jobs:
  fortify_scan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Install and configure Fortify SCA
      - name: Setup Fortify SCA
        run: |
          # Download and install Fortify SCA
          wget https://download.microfocus.com/Download?buildid=505067 -O fortify_sca.zip
          unzip fortify_sca.zip
          export FORTIFY_HOME=$PWD/Fortify
          export PATH=$FORTIFY_HOME/bin:$PATH

          # Configure Fortify SCA
          sourceanalyzer -b myproject -clean
          sourceanalyzer -b myproject .

      # Run the Fortify SCA scan
      - name: Run Fortify SCA Scan
        run: |
          sourceanalyzer -b myproject -scan -f myproject.fpr
      - name: list files
        run: |
          ls -ltr
          
      - name: Upload Scan Results to SSC
        uses: fortify-on-demand/fortify-github-actions/upload-fpr@v1
        with:
          application-name: myproject
          source-filename: myproject.fpr
          ssc-url: <your-ssc-url>
          ssc-username: <your-ssc-username>
          ssc-password: ${{ secrets.SSC_PASSWORD }} # You should add your SSC password as a secret in your repository settings
